[2024-05-18T07:16:57.553+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:06:51.065362+00:00 [queued]>
[2024-05-18T07:16:57.559+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:06:51.065362+00:00 [queued]>
[2024-05-18T07:16:57.560+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-05-18T07:16:57.567+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_transectiondata_to_csv> on 2024-05-18 07:06:51.065362+00:00
[2024-05-18T07:16:57.570+0000] {standard_task_runner.py:60} INFO - Started process 3066 to run task
[2024-05-18T07:16:57.572+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_transection_data', 'save_transectiondata_to_csv', 'manual__2024-05-18T07:06:51.065362+00:00', '--job-id', '444', '--raw', '--subdir', 'DAGS_FOLDER/transection_data.py', '--cfg-path', '/tmp/tmp07g7ea1u']
[2024-05-18T07:16:57.575+0000] {standard_task_runner.py:88} INFO - Job 444: Subtask save_transectiondata_to_csv
[2024-05-18T07:16:57.602+0000] {task_command.py:423} INFO - Running <TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:06:51.065362+00:00 [running]> on host e3e2dc6bc2be
[2024-05-18T07:16:57.646+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_transection_data' AIRFLOW_CTX_TASK_ID='save_transectiondata_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T07:06:51.065362+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T07:06:51.065362+00:00'
[2024-05-18T07:16:57.652+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-18T07:16:57.665+0000] {sql.py:450} INFO - Running statement: SELECT * FROM transsection;, parameters: None
[2024-05-18T07:16:57.711+0000] {sql.py:459} INFO - Rows affected: 5617
[2024-05-18T07:16:57.726+0000] {transection_data.py:371} ERROR - Error saving transaction data to CSV: name 'csv_name' is not defined
[2024-05-18T07:16:57.727+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transection_data.py", line 361, in save_transectiondata_to_csv
    local_filepath = f'/home/ec2-user/{csv_name}'
NameError: name 'csv_name' is not defined
[2024-05-18T07:16:57.735+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=create_transection_data, task_id=save_transectiondata_to_csv, execution_date=20240518T070651, start_date=20240518T071657, end_date=20240518T071657
[2024-05-18T07:16:57.743+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 444 for task save_transectiondata_to_csv (name 'csv_name' is not defined; 3066)
[2024-05-18T07:16:57.789+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-18T07:16:57.800+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
