[2024-05-20T12:21:12.322+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_data_attendance_test.save_att_data_to_postgresql scheduled__2024-05-19T00:00:00+00:00 [queued]>
[2024-05-20T12:21:12.329+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_data_attendance_test.save_att_data_to_postgresql scheduled__2024-05-19T00:00:00+00:00 [queued]>
[2024-05-20T12:21:12.330+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-20T12:21:12.338+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_att_data_to_postgresql> on 2024-05-19 00:00:00+00:00
[2024-05-20T12:21:12.345+0000] {standard_task_runner.py:60} INFO - Started process 1071 to run task
[2024-05-20T12:21:12.352+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_data_attendance_test', 'save_att_data_to_postgresql', 'scheduled__2024-05-19T00:00:00+00:00', '--job-id', '806', '--raw', '--subdir', 'DAGS_FOLDER/api_data_attendance.py', '--cfg-path', '/tmp/tmpg5hj0dxk']
[2024-05-20T12:21:12.356+0000] {standard_task_runner.py:88} INFO - Job 806: Subtask save_att_data_to_postgresql
[2024-05-20T12:21:12.396+0000] {task_command.py:423} INFO - Running <TaskInstance: api_data_attendance_test.save_att_data_to_postgresql scheduled__2024-05-19T00:00:00+00:00 [running]> on host e3e2dc6bc2be
[2024-05-20T12:21:12.443+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_data_attendance_test' AIRFLOW_CTX_TASK_ID='save_att_data_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-19T00:00:00+00:00'
[2024-05-20T12:21:12.468+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-20T12:21:12.478+0000] {sql.py:450} INFO - Running statement: 
                            SELECT booking_id 
                            FROM booking 
                            WHERE remarks = %s 
                                AND booking_start_date = %s 
                                AND booking_start_time >= %s 
                                AND booking_end_time <= %s;
                        , parameters: ('662|ITCS461|3', '2024-01-11', '09:00:00', '12:00:00')
[2024-05-20T12:21:12.485+0000] {sql.py:459} INFO - Rows affected: 0
[2024-05-20T12:21:12.496+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-20T12:21:12.505+0000] {sql.py:450} INFO - Running statement: 
                            INSERT INTO attendance (
                                booking_id,
                                remarks,
                                num_enrolledStd,
                                num_present,
                                percent_present,
                                num_absent,
                                percent_absent,
                                num_leave,
                                percent_leave,
                                class_date,
                                class_start,
                                class_end
                            )
                            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
                        , parameters: (None, '662|ITCS461|3', 56, 53, 94.64, 1, 1.79, 0, 0, '2024-01-11', '09:00:00', '12:00:00')
[2024-05-20T12:21:12.510+0000] {api_data_attendance.py:180} ERROR - Error inserting data to PostgreSQL: column "booking_id" of relation "attendance" does not exist
LINE 3:                                 booking_id,
                                        ^

[2024-05-20T12:21:12.511+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api_data_attendance.py", line 181, in save_att_data_to_postgresql
    raise e
  File "/opt/airflow/dags/api_data_attendance.py", line 160, in save_att_data_to_postgresql
    postgres_hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 453, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.UndefinedColumn: column "booking_id" of relation "attendance" does not exist
LINE 3:                                 booking_id,
                                        ^

[2024-05-20T12:21:12.524+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=api_data_attendance_test, task_id=save_att_data_to_postgresql, execution_date=20240519T000000, start_date=20240520T122112, end_date=20240520T122112
[2024-05-20T12:21:12.535+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 806 for task save_att_data_to_postgresql (column "booking_id" of relation "attendance" does not exist
LINE 3:                                 booking_id,
                                        ^
; 1071)
[2024-05-20T12:21:12.564+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-20T12:21:12.580+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
