[2024-05-20T03:57:25.343+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: temp_humi_dag_csv.save_data_into_db manual__2024-05-20T03:47:17.712928+00:00 [queued]>
[2024-05-20T03:57:25.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: temp_humi_dag_csv.save_data_into_db manual__2024-05-20T03:47:17.712928+00:00 [queued]>
[2024-05-20T03:57:25.350+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-20T03:57:25.357+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_data_into_db> on 2024-05-20 03:47:17.712928+00:00
[2024-05-20T03:57:25.362+0000] {standard_task_runner.py:60} INFO - Started process 2772 to run task
[2024-05-20T03:57:25.364+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'temp_humi_dag_csv', 'save_data_into_db', 'manual__2024-05-20T03:47:17.712928+00:00', '--job-id', '741', '--raw', '--subdir', 'DAGS_FOLDER/ICTTemp_Humi_CSV.py', '--cfg-path', '/tmp/tmpp0pyfio2']
[2024-05-20T03:57:25.367+0000] {standard_task_runner.py:88} INFO - Job 741: Subtask save_data_into_db
[2024-05-20T03:57:25.395+0000] {task_command.py:423} INFO - Running <TaskInstance: temp_humi_dag_csv.save_data_into_db manual__2024-05-20T03:47:17.712928+00:00 [running]> on host e3e2dc6bc2be
[2024-05-20T03:57:25.523+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group4' AIRFLOW_CTX_DAG_ID='temp_humi_dag_csv' AIRFLOW_CTX_TASK_ID='save_data_into_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T03:47:17.712928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T03:47:17.712928+00:00'
[2024-05-20T03:57:25.551+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-20T03:57:25.563+0000] {sql.py:450} INFO - Running statement: 
                INSERT INTO test_temp_and_humi (date, time, temperature, humidity, heat)
                VALUES (%s, %s, %s, %s, %s);
                , parameters: ('2024-01-01', '00:00:00', 23.76, 49.02, 74.77)
[2024-05-20T03:57:25.566+0000] {logging_mixin.py:188} INFO - Error: duplicate key value violates unique constraint "test_temp_and_humi_pkey"
DETAIL:  Key (date, "time")=(2024-01-01, 00:00:00) already exists.
[2024-05-20T03:57:25.567+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-05-20T03:57:25.573+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=temp_humi_dag_csv, task_id=save_data_into_db, execution_date=20240520T034717, start_date=20240520T035725, end_date=20240520T035725
[2024-05-20T03:57:25.624+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-05-20T03:57:25.638+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
