[2024-05-18T08:01:14.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:51:07.448038+00:00 [queued]>
[2024-05-18T08:01:14.995+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:51:07.448038+00:00 [queued]>
[2024-05-18T08:01:14.996+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-05-18T08:01:15.003+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_transectiondata_to_csv> on 2024-05-18 07:51:07.448038+00:00
[2024-05-18T08:01:15.007+0000] {standard_task_runner.py:60} INFO - Started process 6069 to run task
[2024-05-18T08:01:15.010+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_transection_data', 'save_transectiondata_to_csv', 'manual__2024-05-18T07:51:07.448038+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/transection_data.py', '--cfg-path', '/tmp/tmp8m_zif4v']
[2024-05-18T08:01:15.012+0000] {standard_task_runner.py:88} INFO - Job 522: Subtask save_transectiondata_to_csv
[2024-05-18T08:01:15.045+0000] {task_command.py:423} INFO - Running <TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:51:07.448038+00:00 [running]> on host e3e2dc6bc2be
[2024-05-18T08:01:15.091+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_transection_data' AIRFLOW_CTX_TASK_ID='save_transectiondata_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T07:51:07.448038+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T07:51:07.448038+00:00'
[2024-05-18T08:01:15.097+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-18T08:01:15.117+0000] {sql.py:450} INFO - Running statement: SELECT * FROM transsection;, parameters: None
[2024-05-18T08:01:15.170+0000] {sql.py:459} INFO - Rows affected: 5617
[2024-05-18T08:01:15.193+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-18T08:01:15.203+0000] {transection_data.py:377} ERROR - Error saving transaction data to CSV: 'NoneType' object is not iterable
[2024-05-18T08:01:15.205+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transection_data.py", line 367, in save_transectiondata_to_csv
    csv_writer.writerow([i[0] for i in cursor.description])
TypeError: 'NoneType' object is not iterable
[2024-05-18T08:01:15.216+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=create_transection_data, task_id=save_transectiondata_to_csv, execution_date=20240518T075107, start_date=20240518T080114, end_date=20240518T080115
[2024-05-18T08:01:15.224+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 522 for task save_transectiondata_to_csv ('NoneType' object is not iterable; 6069)
[2024-05-18T08:01:15.265+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-18T08:01:15.276+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
