[2024-05-18T07:43:33.412+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:43:27.811309+00:00 [queued]>
[2024-05-18T07:43:33.418+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:43:27.811309+00:00 [queued]>
[2024-05-18T07:43:33.419+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2024-05-18T07:43:33.428+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_transectiondata_to_csv> on 2024-05-18 07:43:27.811309+00:00
[2024-05-18T07:43:33.432+0000] {standard_task_runner.py:60} INFO - Started process 4856 to run task
[2024-05-18T07:43:33.435+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_transection_data', 'save_transectiondata_to_csv', 'manual__2024-05-18T07:43:27.811309+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/transection_data.py', '--cfg-path', '/tmp/tmpketwhw_d']
[2024-05-18T07:43:33.438+0000] {standard_task_runner.py:88} INFO - Job 473: Subtask save_transectiondata_to_csv
[2024-05-18T07:43:33.472+0000] {task_command.py:423} INFO - Running <TaskInstance: create_transection_data.save_transectiondata_to_csv manual__2024-05-18T07:43:27.811309+00:00 [running]> on host e3e2dc6bc2be
[2024-05-18T07:43:33.525+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_transection_data' AIRFLOW_CTX_TASK_ID='save_transectiondata_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-05-18T07:43:27.811309+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-18T07:43:27.811309+00:00'
[2024-05-18T07:43:33.531+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-05-18T07:43:33.541+0000] {sql.py:450} INFO - Running statement: SELECT * FROM transsection;, parameters: None
[2024-05-18T07:43:33.588+0000] {sql.py:459} INFO - Rows affected: 5617
[2024-05-18T07:43:33.609+0000] {transection_data.py:374} ERROR - Error saving transaction data to CSV: [Errno 13] Permission denied: '/Users'
[2024-05-18T07:43:33.610+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/transection_data.py", line 360, in save_transectiondata_to_csv
    os.makedirs(os.path.dirname(csv_file_path), exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'
[2024-05-18T07:43:33.619+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=create_transection_data, task_id=save_transectiondata_to_csv, execution_date=20240518T074327, start_date=20240518T074333, end_date=20240518T074333
[2024-05-18T07:43:33.626+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 473 for task save_transectiondata_to_csv ([Errno 13] Permission denied: '/Users'; 4856)
[2024-05-18T07:43:33.649+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-18T07:43:33.661+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
